#!/bin/bash

NP=8

(cd components && ./prepareBaseMesh && ./prepareBreakwaterMesh)
(cd breakwaterCase && ./run.pre && rm -rf processor* && decomposePar -allRegions)
(cd breakwaterCase && mpirun -np $NP multiCoastFoam -parallel | tee solve.log)

#reconstructPar -allRegions
