#!/bin/bash

NP=4

(cd components && ./prepareBaseMesh)
(cd baseCase && ./run.pre && rm -rf processor* && decomposePar -allRegions)
(cd baseCase && mpirun -np $NP multiPhysicsSWInterFoam -parallel | tee solve.log)

#reconstructPar -allRegions
